<?php

namespace Farmerant\Tests;

use Farmerant\Farmerantcrawl\Listing\Address;
use Farmerant\Farmerantcrawl\Listing\Image;
use Farmerant\Farmerantcrawl\Listing\Product;
use Farmerant\Farmerantcrawl\Listing\Supplier;
use PHPUnit\Framework\TestCase;

/**
 * Class ProductTest
 * @package Farmerant\Tests
 */
class ProductTest extends TestCase
{
    /**
     * @var Product
     */
    private $product;

    /**
     *
     */
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $data = [
            'url' => 'http://www.google.com',
            'title' => 'Product 1',
            'description' => 'Product Description',
            'status' => Product::STATUS_ACTIVE,
            'category' => 'EquipmentSale',
            'websiteName' => 'google',
            'latitude' => 20,
            'longitude' => 20,
            'price' => 2000000,
            'currency' => 'USD',
            'priceDescription' => '',
            'language' => 'AU',
            'sourceCountry' => 'AU',
        ];
        $this->product = new Product();
        $this->product->fill($data);
    }

    protected function validArray($options)
    {
        $this->assertArraySubset(array_merge([
            'url' => 'http://www.google.com',
            'title' => 'Product 1',
            'description' => 'Product Description',
            'status' => 'Active',
            'category' => 'EquipmentSale',
            'website_name' => 'google',
            'latitude' => 20,
            'longitude' => 20,
            'price' => 2000000,
            'currency' => 'USD',
            'price_description' => '',
            'tags' => [],
            'images' => [],
            'suppliers' => [],
        ], $options), $this->product->toArray());
    }

    /** @test */
    public function can_fill_attributes()
    {
        // Assert
        $this->validArray([]);
    }

    /** @test */
    public function add_tags()
    {
        // Act
        $this->product->addTag(['og:title', 'Facebook'])->addTag(['og:description' => 'description']);

        // Assert
        $this->validArray([
            'tags' => [
                ['og:title', 'Facebook'],
                ['og:description' => 'description'],
            ],
        ]);
    }

    /** @test */
    public function add_images()
    {
        // Arrange
        $image = new Image('http://www.google.com/', 'Test', Image::TYPE_GALLERY);
        // Act
        $this->product->addImage($image);

        // Assert
        $this->validArray([
           'images' => [
             [
                 'image_url' => 'http://www.google.com/',
                 'image_name' => 'Test',
                 'image_type' => 'gallery',
             ],
           ],
        ]);
    }

    /** @test */
    public function add_suppliers()
    {
        // Arrange
        $supplier = new Supplier(
            'Supplier',
            'test@example.com',
            'http://www.google.com',
            '+8869999999',
            'http://www.facebook.com'
        );
        $supplier->setAddress(
            new Address(20, 20, 'CHRIS NISWANDEE', 'SMALLSYS INC', '795 E DRAGRAM', 'TUCSON', 85705, 'USA')
        );

        // Act
        $this->product->addSupplier($supplier);

        // Assert
        $this->validArray([
            'suppliers' => [
                [
                    'supplier_name' => 'Supplier',
                    'email' => 'test@example.com',
                    'website' => 'http://www.google.com',
                    'phone' => '+8869999999',
                    'logo_url' => 'http://www.facebook.com',
                    'latitude' => 20,
                    'longitude' => 20,
                    'address_line_1' => 'CHRIS NISWANDEE',
                    'address_line_2' => 'SMALLSYS INC',
                    'address_locality' => '795 E DRAGRAM',
                    'address_state' => 'TUCSON',
                    'address_post_code' => 85705,
                    'address_country' => 'USA',
                ],
            ],
        ]);
    }
}
