<?php

namespace Farmerant\Tests;

use Farmerant\Farmerantcrawl\Listing\Address;
use Farmerant\Farmerantcrawl\Listing\Image;
use Farmerant\Farmerantcrawl\Listing\Product;
use Farmerant\Farmerantcrawl\Listing\Supplier;
use PHPUnit\Framework\TestCase;

/**
 * Class ProductTest
 * @package Farmerant\Tests
 */
class ProductTest extends TestCase
{
    /**
     * @var Product
     */
    private $product;

    /**
     *
     */
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $data = [
            'id' => 14234,
            'url' => 'http://www.google.com',
            'title' => 'Product 1',
            'description' => 'Product Description',
            'status' => Product::STATUS_ACTIVE,
            'primaryCategory' => 'EquipmentSale',
            'websiteName' => 'google',
            'price' => 2000000,
            'currency' => 'USD',
            'currencySymbol' => '$',
            'priceDescription' => '',
            'language' => 'English',
            'sourceCountry' => 'Australia',
        ];
        $this->product = new Product('google');
        $this->product->setAddress(
            new Address(20, 20, 'CHRIS NISWANDEE', 'SMALLSYS INC', '795 E DRAGRAM', 'TUCSON', 85705, 'USA')
        );
        $this->product->fill($data);
    }

    protected function validArray($options)
    {
        $this->assertArraySubset($this->product->toArray(), array_merge([
            'url' => 'http://www.google.com',
            'source_listing_id' => 'google-14234',
            'title' => 'Product 1',
            'description' => 'Product Description',
            'status' => 'Active',
            'primary_category' => 'EquipmentSale',
            'website_name' => 'google',
            'price' => 2000000,
            'currency' => 'USD',
            'currency_symbol' => '$',
            'price_description' => '',
            'language' => 'English',
            'source_country' => 'Australia',
            'lat' => 20,
            'lng' => 20,
            'address_line_1' => 'CHRIS NISWANDEE',
            'address_line_2' => 'SMALLSYS INC',
            'locality' => '795 E DRAGRAM',
            'state' => 'TUCSON',
            'post_code' => 85705,
            'country' => 'USA',
            'tags' => [],
            'images' => [],
            'supplier' => [],
        ], $options));
    }

    /** @test */
    public function can_fill_attributes()
    {
        // Assert
        $this->validArray([]);
    }

    /** @test */
    public function add_tags()
    {
        // Act
        $this->product->addTag(['og:title', 'Facebook'])->addTag(['og:description' => 'description']);

        // Assert
        $this->validArray([
            'tags' => [
                ['og:title', 'Facebook'],
                ['og:description' => 'description'],
            ],
        ]);
    }

    /** @test */
    public function add_images()
    {
        // Arrange
        $image = new Image();
        $image->fill([
            'originUrl' => 'http://www.google.com/',
            'thumbUrl' => 'http://www.google.com/',
            'largeUrl' => 'http://www.google.com/',
            'order' => 1,
            'name' => 'Test',
        ]);
        // Act
        $this->product->addImage($image);

        // Assert
        $this->validArray([
            'images' => [
                [
                    'image_url' => 'http://www.google.com/',
                    'image_name' => 'Test',
                    'image_order' => 1,
                    'image_thumb_url' => 'http://www.google.com/',
                    'image_large_url' => 'http://www.google.com/',
                ],
            ],
        ]);
    }

    /** @test */
    public function add_suppliers()
    {
        // Arrange
        $supplier = new Supplier(
            'Supplier',
            'test@example.com',
            'http://www.google.com',
            '+8869999999',
            'http://www.facebook.com'
        );
        $supplier->setAddress(
            new Address(20, 20, 'CHRIS NISWANDEE', 'SMALLSYS INC', '795 E DRAGRAM', 'TUCSON', 85705, 'USA')
        );

        // Act
        $this->product->setSupplier($supplier);

        // Assert
        $this->validArray([
            'supplier' => [
                'supplier_name' => 'Supplier',
                'email' => 'test@example.com',
                'website' => 'http://www.google.com',
                'phone' => '+8869999999',
                'logo_url' => 'http://www.facebook.com',
                'lat' => 20,
                'lng' => 20,
                'address_line_1' => 'CHRIS NISWANDEE',
                'address_line_2' => 'SMALLSYS INC',
                'locality' => '795 E DRAGRAM',
                'state' => 'TUCSON',
                'post_code' => 85705,
                'country' => 'USA',
                'tags' => [],
                'source_supplier_id' => 'google-14234',
            ],
        ]);
    }
}
